spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource

jcode:
  author: maurice.chen
  basePackage: com.github.dactiv.basic.authentication
  genController: true
  genService: true
  genEntity: true
  genDao: true
  genDoc: false
  genMapperXml: false
  stripPrefix: tb_
  ignoreProperties:
    - id
    - creationTime
  tableNames:
    - tb_authentication_info
    - tb_console_user
    - tb_group
    - tb_member_user