spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmis_message?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 19880602
    type: com.zaxxer.hikari.HikariDataSource

jcode:
  author: maurice.chen
  urlPrefix: authentication
  basePackage: com.xinyouxue.cmis.admin
  genController: true
  genService: true
  genEntity: true
  genDao: true
  genDoc: true
  genMapperXml: false
  stripPrefix: tb_
  ignoreProperties:
    - id
    - creationTime
    - version
  tableNames:
    - tb_comment_message