spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmis_basic?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 19880602
    type: com.zaxxer.hikari.HikariDataSource

jcode:
  author: maurice.chen
  urlPrefix: basic
  basePackage: com.github.dactiv.basic.authentication
  genController: true
  genService: true
  genEntity: true
  genDao: true
  genDoc: true
  genMapperXml: false
  stripPrefix: tb_
  ignoreProperties:
    - id
    - creationTime
  tableNames:
    - tb_attachment
    - tb_lesson_preparation